// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdsObplQjmBnHYU-NlsnlP7pDZrhnbwzY',
    appId: '1:337720262131:android:1891c320122fcad8ad6686',
    messagingSenderId: '337720262131',
    projectId: 'soulscript-81623',
    storageBucket: 'soulscript-81623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsZY5YUXvqYUYjk6qnens2tHJ8TzHvZ54',
    appId: '1:337720262131:ios:f0866e5ea81d8185ad6686',
    messagingSenderId: '337720262131',
    projectId: 'soulscript-81623',
    storageBucket: 'soulscript-81623.firebasestorage.app',
    androidClientId: '337720262131-6uvmqhj0f5qht7828ndk1d00t17gc7n2.apps.googleusercontent.com',
    iosClientId: '337720262131-u7hi5fret5o5pe0rh3mq14gahjeptrcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.soulscript',
  );

}